name: Build and deploy Node.js app to Azure Web App - my-keystone-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
      - name: package
        run: zip -r package.zip . -x .azure .devcontainers .github .gitignore package-lock.json tsconfig.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Download artifact for deployment job
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-keystone-app
          slot-name: Production
          publish-profile: ${{ secrets.PUBLISHING_PROFILE }}
          package: package.zip

      - name: Unzip package
        run: unzip package.zip -d .release/

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Update database
        run: node ./node_modules/@keystone-next/keystone/bin/cli.js prisma db push
        working-directory: .release